application:
  actions: actions
  web: pages
  runtimeManifest:
    packages:
      litmus:
        license: Apache-2.0
        actions:
          preview:
            function: actions/preview/index.js
            web: 'yes'
            runtime: 'nodejs:14'
            inputs:
              LOG_LEVEL: debug
              LITMUS_TOKEN: $LITMUS_TOKEN
            annotations:
              require-adobe-auth: false
              final: true
